ansible_user: ansible
ansible_password: LOCAL@123
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_scheme: https
ansible_winrm_server_cert_validation: ignore
#ansible_winrm_transport: basic
ansible_winrm_transport: kerberos
nexus_username: developer
nexus_password: developer@2019
